// Auto-generated parameters from TFLite flatbuffers in config directory
#ifndef SL_TFLITE_MICRO_MODEL_PARAMETERS_H
#define SL_TFLITE_MICRO_MODEL_PARAMETERS_H

// Definitions generated from magic_wand_model.tflite
#define SL_MAGIC_WAND_MODEL_CLASSES ['wing', 'ring', 'slope', 'negative']
#define SL_MAGIC_WAND_MODEL_DATE "2021-11-02T23:32:22.589Z"
#define SL_MAGIC_WAND_MODEL_HASH "41c4adf3be6917cbcc93cdad73908a06"
#define SL_MAGIC_WAND_MODEL_NAME "tflite_micro_magic_wand"
#define SL_MAGIC_WAND_MODEL_VERSION 1

// Default model parameters
#define SL_DEFAULT_MODEL_CLASSES SL_MAGIC_WAND_MODEL_CLASSES
#define SL_DEFAULT_MODEL_DATE SL_MAGIC_WAND_MODEL_DATE
#define SL_DEFAULT_MODEL_HASH SL_MAGIC_WAND_MODEL_HASH
#define SL_DEFAULT_MODEL_NAME SL_MAGIC_WAND_MODEL_NAME
#define SL_DEFAULT_MODEL_VERSION SL_MAGIC_WAND_MODEL_VERSION

#endif // SL_TFLITE_MICRO_MODEL_PARAMETERS_H
